apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.secret.labels | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secret.data.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.secret.data.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secret.data.POSTGRES_PASSWORD }}
  POSTGRESQL_DATABASE: {{ .Values.secret.data.POSTGRESQL_DATABASE }}
  POSTGRESQL_USERNAME: {{ .Values.secret.data.POSTGRESQL_USERNAME }}
  POSTGRESQL_PASSWORD: {{ .Values.secret.data.POSTGRESQL_PASSWORD }}
