apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-premium-pulp
provisioner: file.csi.azure.com
parameters:
  skuName: Premium_LRS
mountOptions:
  - vers=3.0
  - uid=700
  - gid=700
  - file_mode=0777
  - dir_mode=0777
  - actimeo=30
  - mfsylinks
  - nosharesock
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
