apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.postgres.namespace }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-db-pvc
  namespace: {{ .Values.postgres.namespace }}
  labels:
    app: external-db
spec:
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.postgres.namespace }}
  labels:
    app: external-db
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: external-db
  template:
    metadata:
      labels:
        app: external-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.env.POSTGRES_PASSWORD }}
        ports:
        - containerPort: 5432
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: external-db-pvc
