apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDbSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.externalDbSecret.labels | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB_NAME: {{ .Values.externalDbSecret.data.POSTGRES_DB_NAME }}
  POSTGRES_HOST: {{ .Values.externalDbSecret.data.POSTGRES_HOST }}
  POSTGRES_PASSWORD: {{ .Values.externalDbSecret.data.POSTGRES_PASSWORD }}
  POSTGRES_PORT: {{ .Values.externalDbSecret.data.POSTGRES_PORT }}
  POSTGRES_SSLMODE: {{ .Values.externalDbSecret.data.POSTGRES_SSLMODE }}
  POSTGRES_USERNAME: {{ .Values.externalDbSecret.data.POSTGRES_USERNAME }}
