apiVersion: v1
kind: Pod
metadata:
  name: bash-pod
  namespace: bash
spec:
  containers:
  - name: bash
    image: ghcr.io/mishragulshan999/bash:v1
    command: ["sleep", "172800"]
  imagePullSecrets:
  - name: github-registry-secret
