name: docker login on runner

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

env:
  REGISTRY: ghcr.io
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_BRANCH: main
  CLUSTER_INPUT: ${{ github.event.inputs.cluster }}
  environment: ${{ github.event.inputs.AWS_Environment }}

jobs:
  create_pulp_repo:
    runs-on: ubuntu-latest

    steps: 
      - name: Configure Docker to allow HTTP    
        run: |
              mkdir -p ~/.docker
              echo '{"insecure-registries": ["a64be425b0f424134b057687c4653ba2-2081084264.us-west-2.elb.amazonaws.com:8443"]}' > ~/.docker/config.json
			  
      - name: Docker Login        
        run: |
              echo "v4QkSIh6bXbCqzFf8SSX7tTKZg25rU65" | docker  login a64be425b0f424134b057687c4653ba2-2081084264.us-west-2.elb.amazonaws.com:8443 -u "admin" --password-stdin

      - name: Pull the Image from repo and push it to pulp
        run: |              
              docker  pull busybox
              docker tag busybox a64be425b0f424134b057687c4653ba2-2081084264.us-west-2.elb.amazonaws.com:8443/busybox
              docker push a64be425b0f424134b057687c4653ba2-2081084264.us-west-2.elb.amazonaws.com:8443/busybox
              
      - name: Pull the Image from Pulp
        run: |
              docker pull a64be425b0f424134b057687c4653ba2-2081084264.us-west-2.elb.amazonaws.com:8443/busybox

      - name: List Docker Images
        run: |
              docker image ls

