name: Fetch and Compare Images

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  fetch_images:
    runs-on: [self-hosted, Linux, X64]  # Target your custom self-hosted runner with the custom label 'pulp-k8s'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch container images from GitHub
        run: |
          # Define GitHub repository and token
          GITHUB_REPO="mishragulshan999"
          TOKEN="${{ secrets.GH_ACCESS_TOKEN }}"  # Access your custom secret 'GH_ACCESS_TOKEN'

          # Fetch the list of all container images from GitHub
          IMAGES=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/users/$GITHUB_REPO/packages?package_type=container" \
            | jq -r '.[].name')

          echo "Fetched images from GitHub: $IMAGES"
          echo "$IMAGES" > images.txt

      - name: Fetch Kubernetes deployed tags
        run: |
          # Fetch Kubernetes deployed tags (with full image name)
          K8S_TAGS=$(kubectl get pods --all-namespaces -o=jsonpath='{.items[*].spec.containers[*].image}' | tr ' ' '\n')

          echo "Fetched Kubernetes tags: $K8S_TAGS"
          echo "$K8S_TAGS" > k8s_tags.txt

      - name: Compare GitHub and Kubernetes images
        run: |
          # Compare GitHub versions with Kubernetes deployed tags
          echo "Comparing GitHub images with Kubernetes deployed images..."
          while read -r IMAGE_NAME; do
            echo "Processing image: $IMAGE_NAME"

            # Fetch versions from GitHub
            IMAGE_VERSIONS=$(curl -s -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/users/$GITHUB_REPO/packages/container/$IMAGE_NAME/versions" \
              | jq -r '.[] | "\(.id) \(.metadata.container.tags[0]) \(.created_at)"' | sort -k3)

            # Fetch Kubernetes deployed tags
            K8S_TAGS=$(kubectl get pods --all-namespaces -o=jsonpath='{.items[*].spec.containers[*].image}' | tr ' ' '\n' | grep -E "^ghcr.io/$GITHUB_REPO/$IMAGE_NAME:")

            # Print comparison table
            echo "Image: $IMAGE_NAME"
            echo "GitHub Tag - K8s Deployed? - Push Date"
            echo "$IMAGE_VERSIONS" | while read -r version_id tag created_at; do
              if echo "$K8S_TAGS" | grep -qE "^ghcr.io/$GITHUB_REPO/$IMAGE_NAME:$tag$"; then
                echo "$tag - Yes - $created_at"
              else
                echo "$tag - No - $created_at"
              fi
            done
          done < images.txt

      - name: Delete old image versions
        run: |
          # Function to delete an image version
          delete_image_version() {
            local image_name=$1
            local version_id=$2
            echo "Deleting image version: $image_name - ID: $version_id"

            curl -L -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/users/$GITHUB_REPO/packages/container/$image_name/versions/$version_id"

            echo "Deleted version ID: $version_id"
          }

          # Process each image to delete old versions
          while read -r IMAGE_NAME; do
            echo "Processing image for deletion: $IMAGE_NAME"

            # Fetch versions from GitHub
            IMAGE_VERSIONS=$(curl -s -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/users/$GITHUB_REPO/packages/container/$IMAGE_NAME/versions" \
              | jq -r '.[] | "\(.id) \(.metadata.container.tags[0]) \(.created_at)"' | sort -k3)

            # Fetch Kubernetes deployed tags
            K8S_TAGS=$(kubectl get pods --all-namespaces -o=jsonpath='{.items[*].spec.containers[*].image}' | tr ' ' '\n' | grep -E "^ghcr.io/$GITHUB_REPO/$IMAGE_NAME:")

            # Extract IDs and tags
            TOTAL_VERSIONS=$(echo "$IMAGE_VERSIONS" | wc -l)
            DELETE_COUNT=$((TOTAL_VERSIONS - 5))

            if [[ $DELETE_COUNT -gt 0 ]]; then
              echo "Deleting $DELETE_COUNT old versions for $IMAGE_NAME..."
              echo ""

              # Delete old versions if they are not deployed in Kubernetes
              echo "$IMAGE_VERSIONS" | head -n $DELETE_COUNT | while read -r version_id tag created_at; do
                if ! echo "$K8S_TAGS" | grep -qE "^ghcr.io/$GITHUB_REPO/$IMAGE_NAME:$tag$"; then
                  delete_image_version "$IMAGE_NAME" "$version_id"
                else
                  echo "Skipping deletion of deployed image: $tag"
                fi
              done
            else
              echo "No old images to delete for $IMAGE_NAME."
            fi
          done < images.txt
